import type { Employee, Payslip } from "@/lib/types";
import type { Locale } from "@/lib/i18n";
import { TEAM_META } from "@/lib/constants";
import { monthLabel, rupiah } from "@/lib/utils";

const STR: Record<
  Locale,
  {
    docTitle: string;
    attendance: (present: number, working: number) => string;
    netPayBox: string;
    earnings: string;
    baseSalary: string;
    fixedAllowance: string;
    gross: string;
    overtimeNote: string;
    overtimeLine: (hours: number) => string;
    absenceLine: (days: number) => string;
    deductionsTitle: string;
    bpjsDeductions: string;
    bpjsKes1: string;
    jht2: string;
    jp1: string;
    bpjsEmployeeTotal: string;
    taxDeductions: string;
    pph21: (ptkp: string) => string;
    employerPaid: string;
    bpjsKes4: string;
    jht37: string;
    jp2: string;
    jkk: (pct: string) => string;
    jkm: string;
    takeHome: string;
    transferTo: (bank: string, account: string) => string;
    generated: (timestamp: string) => string;
  }
> = {
  id: {
    docTitle: "SLIP GAJI",
    attendance: (present, working) => `${present} hari hadir dari ${working} hari kerja`,
    netPayBox: "Gaji bersih (take-home pay)",
    earnings: "Pendapatan",
    baseSalary: "Gaji pokok",
    fixedAllowance: "Tunjangan tetap",
    gross: "Total pendapatan",
    overtimeNote: "Lembur yang disetujui pada bulan ini sudah termasuk di gaji.",
    overtimeLine: (hours) => `Lembur (${hours} jam)`,
    absenceLine: (days) => `Potongan absen (${days} hari)`,
    deductionsTitle: "Potongan",
    bpjsDeductions: "Potongan — BPJS (karyawan)",
    bpjsKes1: "BPJS Kesehatan (1%)",
    jht2: "JHT (2%)",
    jp1: "Jaminan Pensiun (1%)",
    bpjsEmployeeTotal: "Total BPJS karyawan",
    taxDeductions: "Potongan — Pajak",
    pph21: (ptkp) => `PPh 21 (TER ${ptkp})`,
    employerPaid: "Ditanggung perusahaan (informasi)",
    bpjsKes4: "BPJS Kesehatan (4%)",
    jht37: "JHT (3.7%)",
    jp2: "Jaminan Pensiun (2%)",
    jkk: (pct) => `JKK (${pct}%)`,
    jkm: "JKM (0.3%)",
    takeHome: "TAKE-HOME PAY",
    transferTo: (bank, account) => `Transfer ke ${bank} · ${account}`,
    generated: (timestamp) => `Dokumen dihasilkan otomatis oleh Treelogy HR System · ${timestamp} WITA`,
  },
  en: {
    docTitle: "PAYSLIP",
    attendance: (present, working) => `${present} days present of ${working} working days`,
    netPayBox: "Net pay (take-home pay)",
    earnings: "Earnings",
    baseSalary: "Base salary",
    fixedAllowance: "Fixed allowance",
    gross: "Total earnings",
    overtimeNote: "Approved overtime this month is already included in the salary.",
    overtimeLine: (hours) => `Overtime (${hours} h)`,
    absenceLine: (days) => `Absence deduction (${days} days)`,
    deductionsTitle: "Deductions",
    bpjsDeductions: "Deductions — BPJS (employee)",
    bpjsKes1: "BPJS Kesehatan (1%)",
    jht2: "JHT (2%)",
    jp1: "Pension (JP) (1%)",
    bpjsEmployeeTotal: "Total employee BPJS",
    taxDeductions: "Deductions — Tax",
    pph21: (ptkp) => `PPh 21 (TER ${ptkp})`,
    employerPaid: "Employer-paid (information)",
    bpjsKes4: "BPJS Kesehatan (4%)",
    jht37: "JHT (3.7%)",
    jp2: "Pension (JP) (2%)",
    jkk: (pct) => `JKK (${pct}%)`,
    jkm: "JKM (0.3%)",
    takeHome: "TAKE-HOME PAY",
    transferTo: (bank, account) => `Transfer to ${bank} · ${account}`,
    generated: (timestamp) => `Automatically generated by Treelogy HR System · ${timestamp} WITA`,
  },
};

// Palet mengikuti tema app (bark/forest/cream).
const BARK: [number, number, number] = [38, 51, 30];
const FOREST: [number, number, number] = [61, 90, 46];
const SOFT: [number, number, number] = [233, 240, 216];
const INK: [number, number, number] = [40, 40, 36];
const MUTED: [number, number, number] = [120, 120, 110];
const LINE: [number, number, number] = [225, 222, 210];

/** rupiah() memakai NBSP dari Intl — ganti spasi biasa agar aman di font PDF. */
const rp = (v: number) => rupiah(v).replace(/ /g, " ");

/**
 * Slip gaji sebagai dokumen PDF (A4), digenerate di sisi klien.
 * jspdf di-import dinamis supaya tidak ikut bundle awal halaman.
 */
async function buildPayslipPdf(slip: Payslip, emp: Employee, locale: Locale = "id") {
  const t = STR[locale];
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  const W = 210;
  const M = 18; // margin kiri/kanan
  const R = W - M; // tepi kanan
  let y = 0;

  // ---- Header brand ----
  doc.setFillColor(...BARK);
  doc.rect(0, 0, W, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("TREELOGY", M, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(200, 210, 190);
  doc.text("HR SYSTEM", M, 21);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(t.docTitle, R, 15, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(200, 210, 190);
  doc.text(monthLabel(slip.period, locale), R, 21, { align: "right" });

  // ---- Identitas karyawan ----
  y = 46;
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(emp.name, M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${emp.nik} · ${emp.position} · ${TEAM_META[emp.team].label}`, M, y + 5.5);
  doc.text(t.attendance(slip.presentDays, slip.workingDays), R, y + 5.5, { align: "right" });

  // ---- Kotak gaji bersih ----
  y += 12;
  doc.setFillColor(...SOFT);
  doc.roundedRect(M, y, R - M, 18, 3, 3, "F");
  doc.setTextColor(...FOREST);
  doc.setFontSize(9);
  doc.text(t.netPayBox, M + 6, y + 7.5);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(rp(slip.netPay), R - 6, y + 12, { align: "right" });
  y += 27;

  // ---- Helper baris & seksi ----
  const section = (title: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(title.toUpperCase(), M, y);
    y += 2;
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.3);
    doc.line(M, y, R, y);
    y += 6;
  };
  const line = (label: string, value: string, opts: { strong?: boolean; muted?: boolean } = {}) => {
    doc.setFont("helvetica", opts.strong ? "bold" : "normal");
    doc.setFontSize(10);
    doc.setTextColor(...(opts.muted ? MUTED : opts.strong ? INK : INK));
    doc.text(label, M, y);
    doc.text(value, R, y, { align: "right" });
    y += 6.5;
  };
  const note = (text: string) => {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(text, M, y);
    y += 7;
  };

  // ---- Pendapatan ----
  section(t.earnings);
  line(t.baseSalary, rp(slip.baseSalary));
  line(t.fixedAllowance, rp(slip.allowance));
  if (slip.overtimePay > 0) line(t.overtimeLine(slip.overtimeHours), rp(slip.overtimePay));
  line(t.gross, rp(slip.grossPay), { strong: true });
  note(t.overtimeNote);

  // ---- Potongan absen (jika ada) ----
  if (slip.absenceDeduction > 0) {
    section(t.deductionsTitle);
    line(t.absenceLine(slip.workingDays - slip.presentDays), `- ${rp(slip.absenceDeduction)}`);
    y += 2;
  }

  // ---- Take-home pay box ----
  doc.setDrawColor(...FOREST);
  doc.setLineWidth(0.5);
  doc.setFillColor(...SOFT);
  doc.roundedRect(M, y, R - M, 14, 3, 3, "FD");
  doc.setTextColor(...FOREST);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(t.takeHome, M + 6, y + 9);
  doc.setFontSize(13);
  doc.text(rp(slip.netPay), R - 6, y + 9, { align: "right" });
  y += 22;

  // ---- Footer ----
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  doc.text(t.transferTo(emp.bankName, emp.bankAccount), W / 2, y, { align: "center" });
  y += 5;
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  const generated = new Intl.DateTimeFormat(locale === "id" ? "id-ID" : "en-US", {
    dateStyle: "long",
    timeStyle: "short",
    timeZone: "Asia/Makassar",
  }).format(new Date());
  doc.text(t.generated(generated), W / 2, y, { align: "center" });

  return doc;
}

/** Unduh slip sebagai file PDF. */
export async function downloadPayslipPdf(slip: Payslip, emp: Employee, locale: Locale = "id"): Promise<void> {
  const doc = await buildPayslipPdf(slip, emp, locale);
  doc.save(`slip-gaji-${emp.nik}-${slip.period}.pdf`);
}

/**
 * Blob URL untuk pratinjau PDF di iframe — pemanggil WAJIB
 * URL.revokeObjectURL() saat pratinjau ditutup.
 */
export async function payslipPdfPreviewUrl(slip: Payslip, emp: Employee, locale: Locale = "id"): Promise<string> {
  const doc = await buildPayslipPdf(slip, emp, locale);
  return URL.createObjectURL(doc.output("blob"));
}
