import type { Locale } from "@/lib/i18n";

/* Satu kamus untuk seluruh modul. Ditaruh terpisah dari komponennya karena
   teks di sini panjang-panjang — ia menjelaskan sebuah alur yang punya akibat
   nyata di toko (import yang tidak bisa dibatalkan per-baris), jadi kalimatnya
   ikut jadi bagian dari pengamannya, bukan hiasan. */

export const STR: Record<Locale, Record<string, string>> = {
  id: {
    // — kartu tarik —
    pullTitle: "Tarik review baru",
    pullLead:
      "Menghubungi endpoint publik yang sama dengan halaman produk Tokopedia — tanpa login, tanpa cookie, tanpa menyentuh Seller Center.",
    pull: "Tarik sekarang",
    pulling: "Menarik…",
    pullingHint: "Ada jeda 3–7 detik antar produk. Biarkan tab ini terbuka.",
    footprint: "Jejak run rutin",
    footprintValue: "±1 permintaan per produk",
    footprintWhy:
      "Review diurutkan terbaru-dulu, jadi begitu satu halaman tidak lagi berisi review baru, sisanya sudah pasti dimiliki dan penyapuan berhenti.",
    cooldownTitle: "Belum waktunya",
    cooldownIn: "Bisa ditarik lagi",
    force: "Tarik lebih awal",
    forceConfirm: "Tarik lebih awal?",
    forceBody:
      "Jeda antar-run sengaja dibuat renggang supaya jejaknya tetap sekecil satu pengunjung biasa. Menariknya lebih awal aman sesekali, tapi jangan dijadikan kebiasaan.",
    forceYes: "Ya, tarik sekarang",
    rejectedTitle: "Tokopedia menolak penarikan terakhir",
    rejectedBody:
      "Ini batas laju, bukan masalah akun. Berhenti hari ini; coba lagi besok. JANGAN menekan tombol berulang kali — itulah satu-satunya hal yang bisa mengubah pola ini dari pengunjung jadi bot.",
    lastRun: "Run terakhir",
    never: "belum pernah",
    requests: "permintaan",
    partialTitle: "Run berhenti di tengah karena waktunya habis",
    partialBody:
      "Yang sudah tertarik tersimpan. Sisanya ikut terambil pada penarikan berikutnya — tidak ada yang hilang.",

    // — angka ringkas —
    inLedger: "Review di ledger",
    inLedgerSub: "seluruh yang pernah tertarik",
    pending: "Belum diekspor",
    pendingSub: "menunggu masuk CSV",
    importable: "Siap import",
    importableSub: "punya teks review",
    starOnly: "Bintang-saja",
    starOnlySub: "ditolak Judge.me (body kosong)",

    // — ekspor —
    exportTitle: "Buat berkas import Judge.me",
    exportLead:
      "Satu review jadi satu baris. Unggah CSV-nya di Judge.me ▸ Settings ▸ Import reviews ▸ Import from a spreadsheet.",
    scope: "Yang diekspor",
    scopeNew: "Belum diekspor",
    scopeAll: "Semua di ledger",
    scopeAllWarn:
      "Mengekspor SEMUA akan mengulang review yang sudah pernah diimport. Judge.me tidak punya dedup bawaan — barisnya akan dobel di toko.",
    nameStyle: "Nama penulis",
    nameMasked: "Nama tersamar",
    nameMaskedHint:
      "Persis yang sudah tampil di Tokopedia (mis. M***c). Tidak menambah informasi baru tentang orangnya.",
    nameAnon: "Anonymous",
    nameAnonHint:
      "Semua baris bernama sama. Di widget toko, ratusan review “Anonymous” justru terbaca seperti review palsu.",
    csv: "Unduh CSV Judge.me",
    xlsx: "Unduh Excel (untuk diperiksa)",
    copySheet: "Salin untuk Sheet",
    skipped: "Unduh yang bintang-saja",
    copied: "Tersalin ✓ Buka Google Sheet, klik sel A1, lalu tempel (⌘V).",
    copyFailed: "Tidak bisa menyalin otomatis. Coba Unduh CSV.",
    exported: "Berkas terunduh.",
    xlsxFailed: "Gagal membuat berkas Excel di perangkat ini — coba Unduh CSV.",
    nothingToExport: "Tidak ada baris untuk diekspor.",
    markedTitle: "sudah ditandai terekspor",
    unmark: "Batalkan penandaan",
    unmarked: "Penandaan dibatalkan — barisnya kembali ke daftar belum diekspor.",
    unmarkHint: "Kalau berkasnya ternyata tidak jadi diimport.",

    // — foto kedaluwarsa —
    photoTitle: "Tautan foto berumur pendek",
    photoBody:
      "Foto review disajikan lewat tautan bertanda tangan yang mati sekitar tiga jam setelah ditarik, dan Judge.me baru mengunduh fotonya saat import diproses. CSV yang ditarik pagi lalu diunggah malam akan masuk tanpa foto, tanpa pesan galat.",
    photoAct: "Import di hari yang sama dengan penarikannya.",
    photoLive: "foto masih hidup",
    photoDead: "foto sudah kedaluwarsa",
    photoRepull: "Tarik ulang untuk menyegarkan tautan fotonya.",

    // — daftar —
    listTitle: "Isi ledger",
    search: "Cari isi review…",
    allProducts: "Semua produk",
    fStatusAll: "Semua status",
    fStatusPending: "Belum diekspor",
    fStatusExported: "Sudah diekspor",
    fBodyAll: "Semua",
    fBodyWith: "Ber-teks",
    fBodyNone: "Bintang-saja",
    noMatch: "Tidak ada review yang cocok dengan saringan ini.",
    emptyTitle: "Ledger masih kosong",
    emptyBody:
      "Tekan “Tarik sekarang” untuk menyapu review yang sudah ada di Tokopedia. Penarikan pertama menyapu semua halaman; sesudah itu tiap run cukup satu permintaan per produk.",
    exportedOn: "Diekspor",
    reply: "Balasan penjual",
    photos: "foto",
    rows: "baris",
    of: "dari",

    // — riwayat run —
    runsTitle: "Riwayat penarikan",
    runsLead: "Jejak operasional — berapa permintaan yang dikirim dan apa hasilnya.",
    noRuns: "Belum ada penarikan.",
    stOk: "Selesai",
    stPartial: "Sebagian",
    stRejected: "Ditolak",
    stFailed: "Gagal",
    stRunning: "Berjalan",
    newLabel: "baru",

    // — peta produk —
    mapTitle: "Peta produk",
    mapLead: "Tokopedia productID → handle produk Shopify. Handle inilah yang dipakai Judge.me mencocokkan review ke produk.",
    mapOpen: "Kelola peta produk",
    mapAdd: "Tambah produk",
    mapId: "Tokopedia productID",
    mapIdHint: "Deretan angka di ujung URL produk Tokopedia.",
    mapHandle: "Handle Shopify",
    mapHandleHint: "Ambil dari URL produk Shopify: /products/<handle>. Pastikan milik vendor Treelogy, bukan vendor uji coba.",
    mapName: "Nama produk",
    mapSave: "Simpan",
    mapSaved: "Peta produk tersimpan ✓",
    mapActive: "Aktif",
    mapInactive: "Nonaktif",
    mapActivate: "Aktifkan",
    mapDeactivate: "Nonaktifkan",
    mapDeactivateHint: "Berhenti ditarik; review lamanya tetap ada di ledger.",
    mapRemove: "Hapus",
    mapRemoveConfirm: "Hapus produk dari peta?",
    mapRemoveBody: "Hanya bisa untuk produk yang belum punya review di ledger.",
    mapEmpty: "Belum ada produk di peta.",
    mapReviews: "review",

    // — panduan import —
    howTitle: "Cara import ke Judge.me",
    how1: "Shopify admin ▸ Apps ▸ Judge.me ▸ Settings ▸ Import reviews ▸ Import from a spreadsheet.",
    how2: "Unggah CSV-nya, lalu petakan kolom sesuai namanya.",
    how3: "Biarkan cf_variant & cf_source TANPA pemetaan — keduanya catatan internal, bukan kolom Judge.me.",
    how4: "Import berjalan ±5 menit dan hasilnya dikirim lewat email.",
    how5: "Salah unggah? Settings ▸ Import reviews ▸ Reviews import log ▸ (⋯) ▸ Delete reviews — menghapus satu batch utuh.",
    expectTitle: "Yang perlu diterima sejak awal",
    expect1: "Review hasil import tidak akan pernah mendapat lencana Verified.",
    expect2: "Review hasil import dikecualikan dari feed rating produk Google Shopping.",
    expect3: "Tetap tampil penuh di widget toko, bintang agregat, dan rich snippet on-site.",
  },

  en: {
    pullTitle: "Pull new reviews",
    pullLead:
      "Calls the same public endpoint the Tokopedia product page uses — no login, no cookies, and never touching Seller Center.",
    pull: "Pull now",
    pulling: "Pulling…",
    pullingHint: "There's a 3–7 second pause between products. Keep this tab open.",
    footprint: "Routine-run footprint",
    footprintValue: "±1 request per product",
    footprintWhy:
      "Reviews come newest-first, so the moment a page holds nothing new, the rest is already owned and the sweep stops.",
    cooldownTitle: "Not yet",
    cooldownIn: "Can pull again",
    force: "Pull early",
    forceConfirm: "Pull early?",
    forceBody:
      "The gap between runs is deliberately wide so the footprint stays as small as a single visitor's. Pulling early is fine once in a while — just don't make it a habit.",
    forceYes: "Yes, pull now",
    rejectedTitle: "Tokopedia rejected the last pull",
    rejectedBody:
      "That's a rate limit, not an account problem. Stop for today and try tomorrow. Do NOT press the button repeatedly — that's the one thing that turns this pattern from a visitor into a bot.",
    lastRun: "Last run",
    never: "never",
    requests: "requests",
    partialTitle: "The run stopped midway because it ran out of time",
    partialBody: "What was pulled is saved. The rest comes in on the next pull — nothing is lost.",

    inLedger: "Reviews in ledger",
    inLedgerSub: "everything ever pulled",
    pending: "Not exported",
    pendingSub: "waiting to go into a CSV",
    importable: "Import-ready",
    importableSub: "has review text",
    starOnly: "Stars only",
    starOnlySub: "rejected by Judge.me (empty body)",

    exportTitle: "Build the Judge.me import file",
    exportLead:
      "One review, one row. Upload the CSV at Judge.me ▸ Settings ▸ Import reviews ▸ Import from a spreadsheet.",
    scope: "What gets exported",
    scopeNew: "Not yet exported",
    scopeAll: "Everything in the ledger",
    scopeAllWarn:
      "Exporting EVERYTHING repeats reviews already imported. Judge.me has no built-in dedup — the rows will double up in your store.",
    nameStyle: "Reviewer name",
    nameMasked: "Masked name",
    nameMaskedHint: "Exactly what Tokopedia already shows (e.g. M***c). It reveals nothing new about the person.",
    nameAnon: "Anonymous",
    nameAnonHint:
      "Every row gets the same name. In the storefront widget, hundreds of “Anonymous” reviews read like fakes.",
    csv: "Download Judge.me CSV",
    xlsx: "Download Excel (to eyeball)",
    copySheet: "Copy for Sheets",
    skipped: "Download the stars-only ones",
    copied: "Copied ✓ Open Google Sheets, click cell A1, then paste (⌘V).",
    copyFailed: "Couldn't copy automatically. Try Download CSV instead.",
    exported: "File downloaded.",
    xlsxFailed: "Couldn't build the Excel file on this device — try Download CSV.",
    nothingToExport: "No rows to export.",
    markedTitle: "marked as exported",
    unmark: "Undo that marking",
    unmarked: "Marking undone — those rows are back in the not-exported list.",
    unmarkHint: "For when the file didn't actually get imported.",

    photoTitle: "Photo links are short-lived",
    photoBody:
      "Review photos are served through signed links that die about three hours after the pull, and Judge.me only downloads them when the import is processed. A CSV pulled in the morning and uploaded at night imports without photos, with no error.",
    photoAct: "Import on the same day you pull.",
    photoLive: "photos still live",
    photoDead: "photos expired",
    photoRepull: "Pull again to refresh the photo links.",

    listTitle: "Ledger contents",
    search: "Search review text…",
    allProducts: "All products",
    fStatusAll: "All statuses",
    fStatusPending: "Not exported",
    fStatusExported: "Exported",
    fBodyAll: "All",
    fBodyWith: "With text",
    fBodyNone: "Stars only",
    noMatch: "No reviews match these filters.",
    emptyTitle: "The ledger is empty",
    emptyBody:
      "Press “Pull now” to sweep the reviews already on Tokopedia. The first pull sweeps every page; after that each run needs just one request per product.",
    exportedOn: "Exported",
    reply: "Seller reply",
    photos: "photos",
    rows: "rows",
    of: "of",

    runsTitle: "Pull history",
    runsLead: "The operational trail — how many requests went out, and what came back.",
    noRuns: "No pulls yet.",
    stOk: "Done",
    stPartial: "Partial",
    stRejected: "Rejected",
    stFailed: "Failed",
    stRunning: "Running",
    newLabel: "new",

    mapTitle: "Product map",
    mapLead:
      "Tokopedia productID → Shopify product handle. That handle is what Judge.me uses to attach each review to a product.",
    mapOpen: "Manage the product map",
    mapAdd: "Add a product",
    mapId: "Tokopedia productID",
    mapIdHint: "The run of digits at the end of the Tokopedia product URL.",
    mapHandle: "Shopify handle",
    mapHandleHint: "From the Shopify product URL: /products/<handle>. Make sure it's the Treelogy vendor, not the test vendor.",
    mapName: "Product name",
    mapSave: "Save",
    mapSaved: "Product map saved ✓",
    mapActive: "Active",
    mapInactive: "Inactive",
    mapActivate: "Activate",
    mapDeactivate: "Deactivate",
    mapDeactivateHint: "Stops being pulled; its old reviews stay in the ledger.",
    mapRemove: "Remove",
    mapRemoveConfirm: "Remove this product from the map?",
    mapRemoveBody: "Only possible for products with no reviews in the ledger.",
    mapEmpty: "No products mapped yet.",
    mapReviews: "reviews",

    howTitle: "How to import into Judge.me",
    how1: "Shopify admin ▸ Apps ▸ Judge.me ▸ Settings ▸ Import reviews ▸ Import from a spreadsheet.",
    how2: "Upload the CSV, then map each column to its matching name.",
    how3: "Leave cf_variant & cf_source UNMAPPED — they're internal notes, not Judge.me columns.",
    how4: "The import runs for ~5 minutes and emails you the result.",
    how5: "Wrong file? Settings ▸ Import reviews ▸ Reviews import log ▸ (⋯) ▸ Delete reviews — removes the whole batch.",
    expectTitle: "What to accept up front",
    expect1: "Imported reviews will never earn the Verified badge.",
    expect2: "Imported reviews are excluded from Google Shopping product-rating feeds.",
    expect3: "They still show in full in the on-site widget, aggregate stars, and on-site rich snippets.",
  },
};
